/**
 * File generated by Magnet rest2mobile 1.1 - Jan 23, 2017 1:59:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.mindfire.quickapiintegration.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.mindfire.quickapiintegration.model.beans.*;

public class WeatherDataFactory extends ControllerFactory<WeatherData> {
  public WeatherDataFactory(MagnetMobileClient magnetClient) {
    super(WeatherData.class, WeatherDataSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller WeatherData
  public static class WeatherDataSchemaFactory extends AbstractControllerSchemaFactory {
    private static WeatherDataSchemaFactory __instance;

    public static synchronized WeatherDataSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new WeatherDataSchemaFactory();
      }

      return __instance;
    }

    private WeatherDataSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getWeather
      JMethod method1 = addMethod("getWeather",
        "data/2.5/weather",
        "GET",
        WeatherResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://api.openweathermap.org");
      method1.addParam("zip",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("appid",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
