/**
 * File generated by Magnet rest2mobile 1.1 - Jan 23, 2017 1:59:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.mindfire.quickapiintegration.model.beans;


/**
 * Generated from json example
{
  "lon" : 77.22,
  "lat" : 28.67
}

 */

public class Coord {

  
  private Double lat;

  
  private Double lon;

  public Double getLat() {
    return lat;
  }
  public Double getLon() {
    return lon;
  }

  /**
  * Builder for Coord
  **/
  public static class CoordBuilder {
    private Coord toBuild = new Coord();

    public CoordBuilder() {
    }

    public Coord build() {
      return toBuild;
    }

    public CoordBuilder lat(Double value) {
      toBuild.lat = value;
      return this;
    }
    public CoordBuilder lon(Double value) {
      toBuild.lon = value;
      return this;
    }
  }
}
