/**
 * File generated by Magnet rest2mobile 1.1 - Jan 23, 2017 1:59:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.mindfire.quickapiintegration.model.beans;


/**
 * Generated from json example
{
  "temp" : 294.68,
  "pressure" : 1020,
  "humidity" : 56,
  "temp_min" : 294.15,
  "temp_max" : 295.15
}

 */

public class Main {

  
  private Integer humidity;

  
  private Integer pressure;

  
  private Double temp;

  
  private Double temp_max;

  
  private Double temp_min;

  public Integer getHumidity() {
    return humidity;
  }
  public Integer getPressure() {
    return pressure;
  }
  public Double getTemp() {
    return temp;
  }
  public Double getTemp_max() {
    return temp_max;
  }
  public Double getTemp_min() {
    return temp_min;
  }

  /**
  * Builder for Main
  **/
  public static class MainBuilder {
    private Main toBuild = new Main();

    public MainBuilder() {
    }

    public Main build() {
      return toBuild;
    }

    public MainBuilder humidity(Integer value) {
      toBuild.humidity = value;
      return this;
    }
    public MainBuilder pressure(Integer value) {
      toBuild.pressure = value;
      return this;
    }
    public MainBuilder temp(Double value) {
      toBuild.temp = value;
      return this;
    }
    public MainBuilder temp_max(Double value) {
      toBuild.temp_max = value;
      return this;
    }
    public MainBuilder temp_min(Double value) {
      toBuild.temp_min = value;
      return this;
    }
  }
}
