/**
 * File generated by Magnet rest2mobile 1.1 - Jan 23, 2017 1:59:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.mindfire.quickapiintegration.model.beans;


/**
 * Generated from json example
{
  "type" : 1,
  "id" : 7809,
  "message" : 0.018,
  "country" : "IN",
  "sunrise" : 1485135790,
  "sunset" : 1485174191
}

 */

public class Sys {

  
  private String country;

  
  private Integer id;

  
  private Double message;

  
  private Integer sunrise;

  
  private Integer sunset;

  
  private Integer type;

  public String getCountry() {
    return country;
  }
  public Integer getId() {
    return id;
  }
  public Double getMessage() {
    return message;
  }
  public Integer getSunrise() {
    return sunrise;
  }
  public Integer getSunset() {
    return sunset;
  }
  public Integer getType() {
    return type;
  }

  /**
  * Builder for Sys
  **/
  public static class SysBuilder {
    private Sys toBuild = new Sys();

    public SysBuilder() {
    }

    public Sys build() {
      return toBuild;
    }

    public SysBuilder country(String value) {
      toBuild.country = value;
      return this;
    }
    public SysBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public SysBuilder message(Double value) {
      toBuild.message = value;
      return this;
    }
    public SysBuilder sunrise(Integer value) {
      toBuild.sunrise = value;
      return this;
    }
    public SysBuilder sunset(Integer value) {
      toBuild.sunset = value;
      return this;
    }
    public SysBuilder type(Integer value) {
      toBuild.type = value;
      return this;
    }
  }
}
