/**
 * File generated by Magnet rest2mobile 1.1 - Jan 23, 2017 1:59:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.mindfire.quickapiintegration.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "coord" : {
    "lon" : 77.22,
    "lat" : 28.67
  },
  "weather" : [ {
    "id" : 711,
    "main" : "Smoke",
    "description" : "smoke",
    "icon" : "50d"
  } ],
  "base" : "stations",
  "main" : {
    "temp" : 294.68,
    "pressure" : 1020,
    "humidity" : 56,
    "temp_min" : 294.15,
    "temp_max" : 295.15
  },
  "visibility" : 1100,
    ...

 */

public class WeatherResult {

  
  private String base;

  
  private Clouds clouds;

  
  private Integer cod;

  
  private Coord coord;

  
  private Integer dt;

  
  private Integer id;

  
  private Main main;

  
  private String name;

  
  private Sys sys;

  
  private Integer visibility;

  
  private List<Weather> weather;

  
  private Wind wind;

  public String getBase() {
    return base;
  }
  public Clouds getClouds() {
    return clouds;
  }
  public Integer getCod() {
    return cod;
  }
  public Coord getCoord() {
    return coord;
  }
  public Integer getDt() {
    return dt;
  }
  public Integer getId() {
    return id;
  }
  public Main getMain() {
    return main;
  }
  public String getName() {
    return name;
  }
  public Sys getSys() {
    return sys;
  }
  public Integer getVisibility() {
    return visibility;
  }
  public List<Weather> getWeather() {
    return weather;
  }
  public Wind getWind() {
    return wind;
  }

  /**
  * Builder for WeatherResult
  **/
  public static class WeatherResultBuilder {
    private WeatherResult toBuild = new WeatherResult();

    public WeatherResultBuilder() {
    }

    public WeatherResult build() {
      return toBuild;
    }

    public WeatherResultBuilder base(String value) {
      toBuild.base = value;
      return this;
    }
    public WeatherResultBuilder clouds(Clouds value) {
      toBuild.clouds = value;
      return this;
    }
    public WeatherResultBuilder cod(Integer value) {
      toBuild.cod = value;
      return this;
    }
    public WeatherResultBuilder coord(Coord value) {
      toBuild.coord = value;
      return this;
    }
    public WeatherResultBuilder dt(Integer value) {
      toBuild.dt = value;
      return this;
    }
    public WeatherResultBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public WeatherResultBuilder main(Main value) {
      toBuild.main = value;
      return this;
    }
    public WeatherResultBuilder name(String value) {
      toBuild.name = value;
      return this;
    }
    public WeatherResultBuilder sys(Sys value) {
      toBuild.sys = value;
      return this;
    }
    public WeatherResultBuilder visibility(Integer value) {
      toBuild.visibility = value;
      return this;
    }
    public WeatherResultBuilder weather(List<Weather> value) {
      toBuild.weather = value;
      return this;
    }
    public WeatherResultBuilder wind(Wind value) {
      toBuild.wind = value;
      return this;
    }
  }
}
