/**
 * File generated by Magnet rest2mobile 1.1 - Jan 23, 2017 1:59:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.mindfire.quickapiintegration.model.beans;


/**
 * Generated from json example
{
  "speed" : 3.1,
  "deg" : 280
}

 */

public class Wind {

  
  private Integer deg;

  
  private Double speed;

  public Integer getDeg() {
    return deg;
  }
  public Double getSpeed() {
    return speed;
  }

  /**
  * Builder for Wind
  **/
  public static class WindBuilder {
    private Wind toBuild = new Wind();

    public WindBuilder() {
    }

    public Wind build() {
      return toBuild;
    }

    public WindBuilder deg(Integer value) {
      toBuild.deg = value;
      return this;
    }
    public WindBuilder speed(Double value) {
      toBuild.speed = value;
      return this;
    }
  }
}
